<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.github.emilioheringer</groupId> <!-- precisa seguir o padrão do JitPack -->
    <artifactId>ComplexNumber</artifactId>
    <version>1.0.0</version> <!-- mesma da tag Git -->

    <name>ComplexNumber</name>
    <description>Biblioteca Java para números complexos com alta precisão</description>
    <url>https://github.com/emilioheringer/ComplexNumber</url>

    <licenses>
        <license>
            <name>The MIT License</name>
            <url>https://opensource.org/licenses/MIT</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>emilioheringer</id>
            <name>Emílio Heringer</name>
        </developer>
    </developers>

    <scm>
        <url>https://github.com/emilioheringer/ComplexNumber</url>
        <connection>scm:git:git://github.com/emilioheringer/ComplexNumber.git</connection>
        <developerConnection>scm:git:ssh://github.com/emilioheringer/ComplexNumber.git</developerConnection>
        <tag>HEAD</tag>
    </scm>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>RELEASE</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
